name: assignment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  flutter: ^3.27.3
  sdk: ^3.6.1

dependencies:
  chopper: ^8.0.4
  collection: ^1.19.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  go_router: ^14.7.2
  json_annotation: ^4.9.0
  leancode_analytics: ^0.1.0
  leancode_cubit_utils: ^0.3.2
  leancode_hooks: ^0.1.1
  logging: ^1.3.0
  provider: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.14
  chopper_generator: ^8.0.4
  go_router_builder: ^2.7.5
  json_serializable: ^6.9.3
  leancode_lint: ^15.0.0
  swagger_dart_code_generator: ^3.0.1

flutter:
  uses-material-design: true
